name: icesat2
channels:
  - conda-forge
dependencies:
  - h5py
  - numpy
  - matplotlib
  - scipy
  - xarray
  - netcdf4
  - dask
  - h5netcdf
#   - gdal
  - pip
  - pip:
    - "--editable=git+https://github.com/friedrichknuth/driveanon.git#egg=driveanon"
